[package]
name = "aoc_2020"
version = "0.1.0"
authors = ["Trangar <victor.koenders@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1.4"
lazy_static = "1.4"
array-init = "1.0"
itertools = "0.9"
